spring:
  data:
    redis:
      database: 0 # Redis 数据库索引（默认为 0）
#      host: 192.168.0.106 # Redis 服务器地址
      host: localhost # Redis 服务器地址
      port: 6333 # Redis 服务器连接端口
      password: S230131144 # Redis 服务器连接密码（默认为空）
      timeout: 5s # 读超时时间
      connect-timeout: 5s # 链接超时时间
      lettuce:
        pool:
          max-active: 200 # 连接池最大连接数
          max-wait: -1ms # 连接池最大阻塞等待时间（负值表示没有限制）
          min-idle: 0 # 连接池中的最小空闲连接
          max-idle: 10 # 连接池中的最大空闲连接

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver # 指定数据库驱动类
#    url: jdbc:mysql://127.0.0.1:3333/xiaohashu?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    username: root # 数据库用户名
#    password: S230131144 # 数据库密码

aliyun: # 接入阿里云（发送短信使用）
  accessKeyId: LTAI5tHhMEM1sGp1PGDnJKGv
  accessKeySecret: ErsfX62lqEhfz0CNEvhQR2Py8gL1GS # 改成你自己的

#logging:
#  level:
#    com.quanxiaoha.xiaohashu.auth.domain.mapper: debug
