#=================================================================
# 对象存储配置
#=================================================================
storage:
  minio:
    endpoint: http://127.0.0.1:9000
    domain: http://127.0.0.1:9001
    accessKey: quanxiaoha
    secretKey: quanxiaoha
  aliyun-oss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    accessKeyId: LTAI5tHhMEM1sGp1PGDnJKGv
    accessKeySecret: ErsfX62lqEhfz0CNEvhQR2Py8gL1GS # 改成你自己的

